service: amp-player-webui

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage}
  region: eu-north-1
  versionFunctions: false

plugins:
  - serverless-s3-sync

custom:
  s3Sync:
    - bucketName: ${self:service}-${self:provider.stage}
      localDir: build
      defaultContentType: text/html
      # WARN!: s3 does not sync metadata changes for files that has not changed.
      params:
        - "**/*.html":
            CacheControl: "no-cache"

resources:
  Resources:
    StaticSite:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:service}-${self:provider.stage}
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: index.html

    StaticSitePolicy:
      Type: "AWS::S3::BucketPolicy"
      DependsOn: StaticSite
      Properties:
        Bucket: !Ref StaticSite
        PolicyDocument:
          Statement:
            - Action: "s3:Get*"
              Effect: Allow
              Resource: "arn:aws:s3:::${self:service}-${self:provider.stage}/*"
              Principal:
                CanonicalUser: !GetAtt CloudFrontOriginAccessIdentity.S3CanonicalUserId

    CloudFrontOriginAccessIdentity:
      Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
      Properties:
        CloudFrontOriginAccessIdentityConfig:
          Comment: ${self:service}-${self:provider.stage}

    OriginRequestPolicy:
      Type: AWS::CloudFront::OriginRequestPolicy
      Properties:
        OriginRequestPolicyConfig:
          Name: remove-host-header
          CookiesConfig:
            CookieBehavior: all
          HeadersConfig:
            HeaderBehavior: allExcept
            Headers:
              - Host
          QueryStringsConfig:
            QueryStringBehavior: all

    CachePolicy:
      Type: AWS::CloudFront::CachePolicy
      Properties:
        CachePolicyConfig:
          Name: Default
          DefaultTTL: 86400 # 24h
          MaxTTL: 86400 # 24h
          MinTTL: 86400 # 24h
          ParametersInCacheKeyAndForwardedToOrigin:
            CookiesConfig:
              CookieBehavior: none
            HeadersConfig:
              HeaderBehavior: none
            QueryStringsConfig:
              QueryStringBehavior: all
            EnableAcceptEncodingGzip: false

    CloudFrontDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          PriceClass: PriceClass_100
          Origins:
            - Id: ${self:service}-${self:provider.stage}
              DomainName: !GetAtt StaticSite.DomainName
              S3OriginConfig:
                OriginAccessIdentity:
                  !Join [
                    "",
                    [
                      "origin-access-identity/cloudfront/",
                      !Ref CloudFrontOriginAccessIdentity,
                    ],
                  ]
            - Id: ${param:apiOriginName}-${self:provider.stage}
              DomainName: !Select [2, !Split ["/", "${param:apiLambdaFunctionUrl}"]] # Removes https:// and trailing /
              CustomOriginConfig:
                HTTPSPort: 443
                OriginProtocolPolicy: https-only
          Enabled: true
          HttpVersion: http2
          DefaultRootObject: index.html
          CustomErrorResponses:
            - ErrorCode: 403
              ResponseCode: 200
              ResponsePagePath: /index.html
            - ErrorCode: 404
              ResponseCode: 200
              ResponsePagePath: /index.html
          DefaultCacheBehavior:
            TargetOriginId: ${self:service}-${self:provider.stage}
            AllowedMethods:
              - GET
              - HEAD
            ForwardedValues:
              QueryString: false
              Cookies:
                Forward: none
            ViewerProtocolPolicy: redirect-to-https
          CacheBehaviors:
            - PathPattern: api/*
              TargetOriginId: amp-player-api-${self:provider.stage}
              OriginRequestPolicyId: !Ref OriginRequestPolicy
              CachePolicyId: !Ref CachePolicy
              AllowedMethods:
                - DELETE
                - GET
                - HEAD
                - OPTIONS
                - PATCH
                - POST
                - PUT
              ForwardedValues:
                QueryString: true
                Headers:
                  - Host
              ViewerProtocolPolicy: redirect-to-https
