service: amp-player-api

frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.11 # Latest supported
  stage: ${opt:stage}
  region: eu-north-1
  versionFunctions: false
  logRetentionInDays: 1

plugins:
  - serverless-offline
  - serverless-python-requirements

custom:
  pythonRequirements:
    usePoetry: true
    requirePoetryLockFile: true

package:
  patterns:
    - "!Makefile"
    - "!node_modules/**"
    - "!package*.json"
    - "!pyproject.toml"
    - "!src/__pycache__/**"
    - "!requirements.txt"
    - "!requirements-dev.txt"

functions:
  handler:
    handler: src.main.handler
    url: true
    events:
      - http:
          path: /{proxy+}
          method: ANY
